# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-17 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biz',
            old_name='neighbourhood',
            new_name='hood',
        ),
    ]
