# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-19 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_remove_biz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
