# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-18 06:48
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='photo',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avi',
            field=pyuploadcare.dj.models.ImageField(null=True),
        ),
    ]
